# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\SSV2 new about window ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(308, 259)
        self.title_label = QtWidgets.QLabel(Dialog)
        self.title_label.setGeometry(QtCore.QRect(70, 0, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.author_label = QtWidgets.QLabel(Dialog)
        self.author_label.setGeometry(QtCore.QRect(90, 50, 111, 16))
        self.author_label.setObjectName("author_label")
        self.gh_label = QtWidgets.QLabel(Dialog)
        self.gh_label.setGeometry(QtCore.QRect(110, 110, 91, 16))
        self.gh_label.setObjectName("gh_label")
        self.gh_button = QtWidgets.QPushButton(Dialog)
        self.gh_button.setGeometry(QtCore.QRect(100, 130, 111, 23))
        self.gh_button.setObjectName("gh_button")
        self.extract_button = QtWidgets.QPushButton(Dialog)
        self.extract_button.setGeometry(QtCore.QRect(100, 200, 111, 23))
        self.extract_button.setObjectName("extract_button")
        self.gull_label = QtWidgets.QLabel(Dialog)
        self.gull_label.setGeometry(QtCore.QRect(120, 180, 81, 20))
        self.gull_label.setObjectName("gull_label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title_label.setText(_translate("Dialog", "Seagull Scaring V2"))
        self.author_label.setText(_translate("Dialog", "By Gabriel Alonso-Holt"))
        self.gh_label.setText(_translate("Dialog", "updates? issues?"))
        self.gh_button.setText(_translate("Dialog", "go to Gabriel\'s github"))
        self.extract_button.setText(_translate("Dialog", "extract gull effects"))
        self.gull_label.setText(_translate("Dialog", "got gull effects?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
