# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\SSV2 new gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 350)
        self.title = QtWidgets.QLabel(Form)
        self.title.setGeometry(QtCore.QRect(160, 40, 131, 21))
        self.title.setObjectName("title")
        self.timer_entry = QtWidgets.QLineEdit(Form)
        self.timer_entry.setGeometry(QtCore.QRect(20, 100, 113, 20))
        self.timer_entry.setObjectName("timer_entry")
        self.timer_label = QtWidgets.QLabel(Form)
        self.timer_label.setGeometry(QtCore.QRect(30, 80, 81, 16))
        self.timer_label.setObjectName("timer_label")
        self.sounds = QtWidgets.QComboBox(Form)
        self.sounds.setGeometry(QtCore.QRect(170, 100, 91, 22))
        self.sounds.setCurrentText("")
        self.sounds.setObjectName("sounds")
        self.select_sound_label = QtWidgets.QLabel(Form)
        self.select_sound_label.setGeometry(QtCore.QRect(170, 80, 91, 16))
        self.select_sound_label.setObjectName("select_sound_label")
        self.min_time_entry = QtWidgets.QLineEdit(Form)
        self.min_time_entry.setGeometry(QtCore.QRect(20, 150, 113, 20))
        self.min_time_entry.setObjectName("min_time_entry")
        self.max_time_entry = QtWidgets.QLineEdit(Form)
        self.max_time_entry.setGeometry(QtCore.QRect(20, 200, 113, 20))
        self.max_time_entry.setObjectName("max_time_entry")
        self.min_time_label = QtWidgets.QLabel(Form)
        self.min_time_label.setGeometry(QtCore.QRect(30, 130, 71, 16))
        self.min_time_label.setObjectName("min_time_label")
        self.max_time_label = QtWidgets.QLabel(Form)
        self.max_time_label.setGeometry(QtCore.QRect(30, 180, 71, 16))
        self.max_time_label.setObjectName("max_time_label")
        self.scare_button = QtWidgets.QPushButton(Form)
        self.scare_button.setGeometry(QtCore.QRect(140, 270, 131, 23))
        self.scare_button.setObjectName("scare_button")
        self.volume_slider = QtWidgets.QSlider(Form)
        self.volume_slider.setGeometry(QtCore.QRect(330, 110, 22, 160))
        self.volume_slider.setMinimum(1)
        self.volume_slider.setMaximum(100)
        self.volume_slider.setOrientation(QtCore.Qt.Vertical)
        self.volume_slider.setObjectName("volume_slider")
        self.volume_label = QtWidgets.QLabel(Form)
        self.volume_label.setGeometry(QtCore.QRect(320, 80, 47, 13))
        self.volume_label.setObjectName("volume_label")
        self.about_button = QtWidgets.QPushButton(Form)
        self.about_button.setGeometry(QtCore.QRect(320, 300, 51, 21))
        self.about_button.setObjectName("about_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.title.setText(_translate("Form", "Seagull Scaring"))
        self.timer_entry.setToolTip(_translate("Form", "Time to run the program for. Recommended: 2700 seconds."))
        self.timer_label.setText(_translate("Form", "Timer in seconds:"))
        self.select_sound_label.setText(_translate("Form", "Select your sound:"))
        self.min_time_label.setText(_translate("Form", "Minimum time:"))
        self.max_time_label.setText(_translate("Form", "Maximum time:"))
        self.scare_button.setToolTip(_translate("Form", "Start scaring the seagulls."))
        self.scare_button.setText(_translate("Form", "scare the gulls"))
        self.volume_slider.setToolTip(_translate("Form", "Change the volume of the seagull sound."))
        self.volume_label.setText(_translate("Form", "Volume"))
        self.about_button.setText(_translate("Form", "about"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
