# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\SSV2 new log window ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        self.seagull_log = QtWidgets.QTextEdit(Dialog)
        self.seagull_log.setGeometry(QtCore.QRect(0, 0, 291, 301))
        self.seagull_log.setObjectName("seagull_log")
        self.scroll_bar = QtWidgets.QScrollBar(Dialog)
        self.scroll_bar.setGeometry(QtCore.QRect(290, 0, 16, 291))
        self.scroll_bar.setOrientation(QtCore.Qt.Vertical)
        self.scroll_bar.setObjectName("scroll_bar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.scroll_bar.setToolTip(_translate("Dialog", "Scroll through the seagull log."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
