# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ssv2_autostart_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(240, 309)
        self.countdown = QtWidgets.QTextEdit(Dialog)
        self.countdown.setGeometry(QtCore.QRect(0, 0, 241, 271))
        self.countdown.setObjectName("countdown")
        self.abort_button = QtWidgets.QPushButton(Dialog)
        self.abort_button.setGeometry(QtCore.QRect(0, 267, 241, 41))
        self.abort_button.setObjectName("abort_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Autostart"))
        self.abort_button.setToolTip(_translate("Dialog", "Abort the automatic seagull scaring."))
        self.abort_button.setText(_translate("Dialog", "abort seagull scaring"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
