# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ssv2_announcement_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(482, 262)
        self.buttons = QtWidgets.QDialogButtonBox(Dialog)
        self.buttons.setGeometry(QtCore.QRect(10, 220, 461, 32))
        self.buttons.setOrientation(QtCore.Qt.Horizontal)
        self.buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttons.setObjectName("buttons")
        self.message = QtWidgets.QTextEdit(Dialog)
        self.message.setGeometry(QtCore.QRect(10, 30, 461, 181))
        self.message.setObjectName("message")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 461, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        self.buttons.accepted.connect(Dialog.accept) # type: ignore
        self.buttons.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Send announcement"))
        Dialog.setToolTip(_translate("Dialog", "Send a Seagull Wars public service announcement."))
        self.label.setText(_translate("Dialog", "Send a Seagull Wars public service announcement. Type your message below:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
